version: "3.9"
services:
  mysql1:
    image: mysql:5.7
    container_name: db1
    ports:
    - "3306:3306"
    volumes:
      - .:/usr/src/db
    environment:
      MYSQL_ROOT_PASSWORD: admin
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-padmin"]
      timeout: 20s
      retries: 10
  nodejs1:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server6
    ports:
      - "80:8080"
    volumes:
      - ./server:/usr/src/server
    depends_on:
      mysql1:
        condition: service_healthy
    stdin_open: true
    tty: true
  nodejs2:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client6
    ports:
      - "81:3000"
    volumes:
      - ./client:/usr/src/app/src
    depends_on:
      mysql1:
        condition: service_healthy
    stdin_open: true
    tty: true
